spring:
  application:
    name: casse
  elasticsearch:
    uris: http://localhost:9200
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
#          facebook:
#            client-id: YOUR_FACEBOOK_CLIENT_ID
#            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
#            scope: public_profile, email
#          instagram:
#            client-id: YOUR_INSTAGRAM_CLIENT_ID
#            client-secret: YOUR_INSTAGRAM_CLIENT_SECRET
#            scope: user_profile
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#        provider:
#          facebook:
#            authorization-uri: https://www.facebook.com/v11.0/dialog/oauth
#            token-uri: https://graph.facebook.com/v11.0/oauth/access_token
#            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
#          instagram:
#            authorization-uri: https://api.instagram.com/oauth/authorize
#            token-uri: https://api.instagram.com/oauth/access_token
#            user-info-uri: https://graph.instagram.com/me?fields=id,username

  session:
    store-type: redis
    redis:
      namespace: casse-sessions
      configure-action: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  data:
    redis:
      url: redis://redis:6666

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CASSE_EMAIL}
    password: ${CASSE_EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

casse:
  pending:
    approval:
      ttl: P30D
  approvers: approvers-emails-as-comma-separated-string
  base-url: ${CASSE_BASE_URL} # Changed to environment variable

server:
  tomcat:
    max-swallow-size=100MB:

cloudflare:
  r2:
    access-key: ${CLOUDFARE_ACCESS_KEY}
    secret-key: ${CLOUDFARE_SECRET_KEY}
    region: auto
    bucket-name: casse-audio
    endpoint: https://${CLOUDFARE_ACCOUNT_ID}.r2.cloudflarestorage.com
